version: '3.8'

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: coinflowuser
            POSTGRES_PASSWORD: coinflowpassword
            POSTGRES_DB: coinflowdb
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        driver: local
